services:
  # A Docker web service
  - type: web
    name: bwhero-proxy
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bwhero_proxy:app --host 0.0.0.0 --port $PORT